### ISSUE TITLE
Missing 1.9.0 release.

### ISSUE THREAD

**Issue by mobinmob** [atweiden/voidvault#6]
Documentation refers  to  version 1.9.0, but it is not available in https://github.com/atweiden/voidvault/releases .

**Comment by atweiden** [comment]
It's been awhile since I've made a vv release. Should I make one?

Note the 1.8.0 release documentation should mention version 1.8.0 IIRC. In the future, I expected to have the same dynamic where the released version contains documentation stating the correct, current version. The latest master branch would contain docs pointing to the next (unreleased) version. But I suppose this creates confusion since most users will browse the vv docs online at GitHub where they'll encounter the master branch by default. I'll stop with this, then, because it creates a mismatch of expectations.

I'm going to create a 1.9.0 release now, mainly because I'm in a good position to do so. I haven't tested this 1.9.0 release tarball, though, so if you could report back with your results, it'd be much appreciated. I have been using the latest vv unofficially, unreleased versions of it, across x86_64 and x86_64-musl in VirtualBox over the past several months. However, I have not bootstrapped a new vbox using the latest release of Perl 6, 2019.11. In the past, I have had issues with upstream Perl 6 releases breaking my code in unexpected ways.

Note rakudo-2019.11 adds another environment variable which is necessary to export before using vv. See: https://github.com/void-linux/void-packages/pull/17073

**Comment by atweiden** [comment]
1.9.0 is available. Thanks for bringing this issue to my attention.

**Comment by mobinmob** [comment]
> It's been awhile since I've made a vv release. Should I make one?
> 
> Note the 1.8.0 release documentation should mention version 1.8.0 IIRC. In the future, I expected to have the same dynamic where the released version contains documentation stating the correct, current version. The latest master branch would contain docs pointing to the next (unreleased) version. But I suppose this creates confusion since most users will browse the vv docs online at GitHub where they'll encounter the master branch by default. I'll stop with this, then, because it creates a mismatch of expectations.

That is exactly how I discovered the problem :) Ι told a friend to follow the procedure at INSTALL.md and he could not fetch the tarball for 1.9.0.

**Comment by mobinmob** [comment]
> 1.9.0 is available. Thanks for bringing this issue to my attention.

Thank you! I will do some tests with the latest -unofficial- isos and report back for any issues.
