### ISSUE TITLE
Grub load error

### ISSUE THREAD

**Issue by scobiehague** [atweiden/voidvault#7]
Hi. I tried the latest stable version of this script from your custom iso. The EFI install did not create any boot entries, so I tried a BIOS install and receive a 'Grub load error' message.

The install appeared to work correctly (and I checked the integrity of the USB), although it did mention some dracut modules would not be installed due to missing files, so is that the problem?

**Comment by atweiden** [comment]
> Hi. I tried the latest stable version of this script from your custom iso. The EFI install did not create any boot entries, so I tried a BIOS install and receive a 'Grub load error' message.

This is interesting to me, as I've successfully bootstrapped the latest stable version of vv using vbox several times over, see: [testing matrix](README.md#voidvault).

The only thing that immediately comes to mind regarding this matter is that voidvault-1.10.0 switched to using zstd btrfs compression: zstd compression on `/boot` is incompatible with grub versions earlier than 2.04.

I last updated my [custom iso](https://github.com/atweiden/voidiso/releases) over six months before [grub-2.04 shipped in void](https://github.com/void-linux/void-packages/commit/6b04cf5353ec2e9eb41367654704a09b91343ab0). If for some reason vv is not using or installing the latest version of grub during the bootstrap, this error may result.

However, I don't know why vv wouldn't be updating its grub during installation, given the code explicitly updates grub as a dependency during the bootstrap: https://github.com/atweiden/voidvault/blob/362e86eed0de2242790b816da289f82b11e1a563/lib/Voidvault/Bootstrap.pm6#L83.

If you could, please try bootstrapping again using the [official iso](https://a-hel-fi.m.voidlinux.org/live/current/void-live-x86_64-20181111.iso) just to be sure this issue is not being caused by a corner case with my aging custom iso. I test vv using the official isos. The official isos should work. Just be sure to add `rd.live.overlay.overlayfs=1` to the kernel command line on livecd boot up per the documentation, and then proceed as normal.

I apologize for any inconvenience.

> The EFI install did not create any boot entries, so I tried a BIOS install and receive a 'Grub load error' message.

Also, could you clarify what you mean by this? Note there is no BIOS install mode or EFI install mode in vv; it installs both grub bios and efi support simultaneously. Are you bootstrapping void using `voidvault new` without modifying the source code?

**Comment by atweiden** [comment]
Just thought of the other, more likely, possibility:

If you're using the voidvault source code shipped with my aging custom iso, which it sounds like you are and which is highly inadvisable, that version of voidvault does not specify `cryptsetup luksFormat --types luks1` (see: https://github.com/atweiden/voidvault/commit/718488a85cd8cac9bc96d445d80f21c861eca0f5). Not specifying this cryptsetup option worked perfectly well prior to cryptsetup-2.1.0. In cryptsetup-2.1.0 and later, cryptsetup began to default to `--types luks2`, which is incompatible with Grub, including recent versions of Grub.

Please ensure you're using the latest stable version of voidvault, which is 1.10.0. Use it from the official isos, and you should be fine. vv-1.10.0 should also work fine from my custom void iso though, just make sure you grab that version and don't use something from 2018.

**Comment by scobiehague** [comment]
Hi. I already tried using the official ISO you link in the README.md, with the same problems. I'll try to log more output. 

> If you're using the voidvault source code shipped with my aging custom iso

I've always used curl to get the 1.10.0 sourcecode as instructed.

> Also, could you clarify what you mean by this? Note there is no BIOS install mode or EFI install mode in vv; it installs both grub bios and efi support simultaneously. Are you bootstrapping void using voidvault new without modifying the source code?

Yes I'm running things unmodified following all the instructions. I only meant that I tried installing once with my BIOS set for UEFI and once with it set for CSM compatibility mode.

I've also tried mounting the EFI partition to change the location of the .efi file to see if my BIOS picks it up as suggested [here](https://wiki.voidlinux.org/Installation_on_UEFI,_via_chroot) . 

Thanks for the help.

**Comment by scobiehague** [comment]
I've successfully installed voidvault on another computer, so it is probably a problem with the BIOS implementation on my Lenovo g505s laptop. I will post back when I get to the bottom of it.

On another note, are the following messages in the successful install anything to worry about?

> dracut: Executing: /usr/bin/dracut --force --kver 5.3.18_1
dracut: dracut module 'bootchart' will not be installed, because command '/sbin/bootchartd' could not be found!
dracut: dracut module 'modsign' will not be installed, because command 'keyctl' could not be found!
dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!
dracut: dracut module 'plymouth' will not be installed, because it's in the list to be omitted!
dracut: dracut module 'lvmmerge' will not be installed, because command 'lvm' could not be found!
dracut: dracut module 'dmraid' will not be installed, because command 'dmraid' could not be found!
dracut: dracut module 'dmsquash-live-ntfs' will not be installed, because command 'ntfs-3g' could not be found!
dracut: dracut module 'lvm' will not be installed, because command 'lvm' could not be found!
dracut: dracut module 'mdraid' will not be installed, because command 'mdadm' could not be found!
dracut: dracut module 'multipath' will not be installed, because command 'multipath' could not be found!
dracut: dracut module 'stratis' will not be installed, because command 'stratisd-init' could not be found!
dracut: dracut module 'stratis' will not be installed, because command 'thin_check' could not be found!
dracut: dracut module 'stratis' will not be installed, because command 'thin_repair' could not be found!
dracut: dracut module 'crypt-gpg' will not be installed, because command 'gpg' could not be found!
dracut: dracut module 'cifs' will not be installed, because command 'mount.cifs' could not be found!
dracut: dracut module 'fcoe-uefi' will not be installed, because command 'dcbtool' could not be found!
dracut: dracut module 'fcoe-uefi' will not be installed, because command 'fipvlan' could not be found!
dracut: dracut module 'fcoe-uefi' will not be installed, because command 'lldpad' could not be found!
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: dracut module 'usrmount' will not be installed, because it's in the list to be omitted!

**Comment by atweiden** [comment]
> I've successfully installed voidvault on another computer, so it is probably a problem with the BIOS implementation on my Lenovo g505s laptop. I will post back when I get to the bottom of it.

It very well could be the case your particular 64-bit laptop requires a 32-bit GRUB installation.

I've intentionally [excluded support](https://github.com/atweiden/voidvault/commit/2dd1ed4d4e8f321e05ada0963833b751c481b0e5) for such hardware to this date.

I would not object to a pull request implementing a flag handling this edge case for the completely haywire machines requiring it, but depending on how much of an eye-sore it inflicts on the CLI, I may or may not merge it. I would really only consider implementing it if I myself located a modern and compelling piece of hardware that had a credible explanation for this insane requirement.

Sorry.

The dracut output is fine.

**Comment by scobiehague** [comment]
So I unscrewed the SSD holding the voidvault installation from the secondary bay caddy in the laptop to put it back in the primary slot and voidvault booted. Laptop BIOS must not be able to boot properly from a secondary drive. Sorry to waste your time, and I am now enjoying the voidvault installation on two computers.

**Comment by atweiden** [comment]
Sounds like a more generally applicable case than I expected. I'll test this if/when I obtain the requisite hardware. Apologies for any hassle caused.
